#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $CYBER_REPO == "CYBERWORRIORSBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0NZQkVSV09SUklPUlMvQ1lCRVJXT1JSSU9SU1VTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw==" | base64 -d
    elif [[ $CYBER_REPO == "CYBERWORRIORSBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0NZQkVSV09SUklPUlMvQ1lCRVJXT1JSSU9SU1VTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw==" | base64 -d
    elif [[ $CYBER_REPO =~ $regex ]]
    then
        if [[ $CYBER_REPO_BRANCH ]]
        then
            echo "${CYBER_REPO}/archive/${CYBER_REPO_BRANCH}.zip"
        else
            echo "${CYBER_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0NZQkVSV09SUklPUlMvQ1lCRVJXT1JSSU9SU1VTRVJCT1QvYXJjaGl2ZS9tYXN0ZXIuemlw==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="CYBERWORRIORSBOT.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    CYBERPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $CYBERPATH
    echo "    Starting CYBERWORRIORSBOT    "
    echo "
    CYBERWORRIORSBOT
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
